import { withInstall } from '@/utils';
// import _FieldButton from './components/FieldButton.vue';
import _FieldCascader from './components/FieldCascader.vue';
import _FieldCheckbox from './components/FieldCheckbox.vue';
import _FieldDatePicker from './components/FieldDatePicker.vue';
import _FieldInput from './components/FieldInput.vue';
import _FieldInputNumber from './components/FieldInputNumber.vue';
import _FieldInputNumberRange from './components/FieldInputNumberRange.vue';
import _FieldLabel from './components/FieldLabel.vue';
import _FieldLink from './components/FieldLink.vue';
import _FieldRadio from './components/FieldRadio.vue';
import _FieldSelect from './components/FieldSelect.vue';
import _FieldTimePicker from './components/FieldTimePicker.vue';
// import _FieldUpload from './components/FieldUpload.vue';
import _FieldSwitch from './components/FieldSwitch.vue';
import _FieldTreeSelect from './components/FieldTreeSelect.vue';

// export const FieldButton = withInstall(_FieldButton);
export const FieldCascader = withInstall(_FieldCascader);
export const FieldCheckbox = withInstall(_FieldCheckbox);
export const FieldDatePicker = withInstall(_FieldDatePicker);
export const FieldInput = withInstall(_FieldInput);
export const FieldInputNumber = withInstall(_FieldInputNumber);
export const FieldInputNumberRange = withInstall(_FieldInputNumberRange);
export const FieldLabel = withInstall(_FieldLabel);
export const FieldLink = withInstall(_FieldLink);
export const FieldRadio = withInstall(_FieldRadio);
export const FieldSelect = withInstall(_FieldSelect);
export const FieldTimePicker = withInstall(_FieldTimePicker);
// export const FieldUpload = withInstall(_FieldUpload);
export const FieldSwitch = withInstall(_FieldSwitch);
export const FieldTreeSelect = withInstall(_FieldTreeSelect);
