/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminPage: typeof import('./../layouts/AdminPage.vue')['default']
    AppHeader: typeof import('./../components/app/AppHeader.vue')['default']
    ContentPage: typeof import('./../layouts/ContentPage.vue')['default']
    NotPermission: typeof import('./../components/app/NotPermission.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./../components/app/SidebarMenu.vue')['default']
    SidebarMenuItem: typeof import('./../components/app/SidebarMenuItem.vue')['default']
    TabBar: typeof import('./../components/app/TabBar/TabBar.vue')['default']
    TabBarItem: typeof import('./../components/app/TabBar/TabBarItem.vue')['default']
  }
}
