/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/dashboard/workplace': RouteRecordInfo<'/dashboard/workplace', '/dashboard/workplace', Record<never, never>, Record<never, never>>,
    '/multilevel_menu_example/page1': RouteRecordInfo<'/multilevel_menu_example/page1', '/multilevel_menu_example/page1', Record<never, never>, Record<never, never>>,
    '/multilevel_menu_example/page2/page2-1': RouteRecordInfo<'/multilevel_menu_example/page2/page2-1', '/multilevel_menu_example/page2/page2-1', Record<never, never>, Record<never, never>>,
    '/multilevel_menu_example/page2/page2-2': RouteRecordInfo<'/multilevel_menu_example/page2/page2-2', '/multilevel_menu_example/page2/page2-2', Record<never, never>, Record<never, never>>,
    '/multilevel_menu_example/page2/page2-3/page2-3-1': RouteRecordInfo<'/multilevel_menu_example/page2/page2-3/page2-3-1', '/multilevel_menu_example/page2/page2-3/page2-3-1', Record<never, never>, Record<never, never>>,
    '/multilevel_menu_example/page2/page2-3/page2-3-2': RouteRecordInfo<'/multilevel_menu_example/page2/page2-3/page2-3-2', '/multilevel_menu_example/page2/page2-3/page2-3-2', Record<never, never>, Record<never, never>>,
    '/operation/': RouteRecordInfo<'/operation/', '/operation', Record<never, never>, Record<never, never>>,
    '/reload': RouteRecordInfo<'/reload', '/reload', Record<never, never>, Record<never, never>>,
  }
}
