/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'notFound': RouteRecordInfo<'notFound', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'workplace': RouteRecordInfo<'workplace', '/dashboard/workplace', Record<never, never>, Record<never, never>>,
    'multiDialogManBackground': RouteRecordInfo<'multiDialogManBackground', '/multiDialogMan/background', Record<never, never>, Record<never, never>>,
    'multiDialogManSolution': RouteRecordInfo<'multiDialogManSolution', '/multiDialogMan/solution', Record<never, never>, Record<never, never>>,
    '/multiDialogMan/solutions/DialogMuster/DialogComp': RouteRecordInfo<'/multiDialogMan/solutions/DialogMuster/DialogComp', '/multiDialogMan/solutions/DialogMuster/DialogComp', Record<never, never>, Record<never, never>>,
    '/reload': RouteRecordInfo<'/reload', '/reload', Record<never, never>, Record<never, never>>,
  }
}
